//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_ws", Namespace="http://webservice.facturatech.co/")]
    public partial class response_ws : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string transaccionIDField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transaccionID
        {
            get
            {
                return this.transaccionIDField;
            }
            set
            {
                this.transaccionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_docs", Namespace="http://webservice.facturatech.co/")]
    public partial class response_docs : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string statusField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_xml", Namespace="http://webservice.facturatech.co/")]
    public partial class response_xml : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData
        {
            get
            {
                return this.resourceDataField;
            }
            set
            {
                this.resourceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_pdf", Namespace="http://webservice.facturatech.co/")]
    public partial class response_pdf : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData
        {
            get
            {
                return this.resourceDataField;
            }
            set
            {
                this.resourceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_cufe", Namespace="http://webservice.facturatech.co/")]
    public partial class response_cufe : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData
        {
            get
            {
                return this.resourceDataField;
            }
            set
            {
                this.resourceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_qr", Namespace="http://webservice.facturatech.co/")]
    public partial class response_qr : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData
        {
            get
            {
                return this.resourceDataField;
            }
            set
            {
                this.resourceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="response_qr_image_file", Namespace="http://webservice.facturatech.co/")]
    public partial class response_qr_image_file : object
    {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string MsgerrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resourceData
        {
            get
            {
                return this.resourceDataField;
            }
            set
            {
                this.resourceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Msgerror
        {
            get
            {
                return this.MsgerrorField;
            }
            set
            {
                this.MsgerrorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.facturatech.co/", ConfigurationName="ServiceReference1.WSV2PROSoap")]
    public interface WSV2PROSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFile", ReplyAction="*")]
        ServiceReference1.uploadInvoiceFileResponse uploadInvoiceFile(ServiceReference1.uploadInvoiceFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.uploadInvoiceFileResponse> uploadInvoiceFileAsync(ServiceReference1.uploadInvoiceFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFileLayout", ReplyAction="*")]
        ServiceReference1.uploadInvoiceFileLayoutResponse uploadInvoiceFileLayout(ServiceReference1.uploadInvoiceFileLayoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/uploadInvoiceFileLayout", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.uploadInvoiceFileLayoutResponse> uploadInvoiceFileLayoutAsync(ServiceReference1.uploadInvoiceFileLayoutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/documentStatusFile", ReplyAction="*")]
        ServiceReference1.documentStatusFileResponse documentStatusFile(ServiceReference1.documentStatusFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/documentStatusFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.documentStatusFileResponse> documentStatusFileAsync(ServiceReference1.documentStatusFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadXMLFile", ReplyAction="*")]
        ServiceReference1.downloadXMLFileResponse downloadXMLFile(ServiceReference1.downloadXMLFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadXMLFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.downloadXMLFileResponse> downloadXMLFileAsync(ServiceReference1.downloadXMLFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadPDFFile", ReplyAction="*")]
        ServiceReference1.downloadPDFFileResponse downloadPDFFile(ServiceReference1.downloadPDFFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadPDFFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.downloadPDFFileResponse> downloadPDFFileAsync(ServiceReference1.downloadPDFFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadCUFEFile", ReplyAction="*")]
        ServiceReference1.downloadCUFEFileResponse downloadCUFEFile(ServiceReference1.downloadCUFEFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadCUFEFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.downloadCUFEFileResponse> downloadCUFEFileAsync(ServiceReference1.downloadCUFEFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRFile", ReplyAction="*")]
        ServiceReference1.downloadQRFileResponse downloadQRFile(ServiceReference1.downloadQRFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.downloadQRFileResponse> downloadQRFileAsync(ServiceReference1.downloadQRFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://webservice.facturatech.co/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRImageFile", ReplyAction="*")]
        ServiceReference1.downloadQRImageFileResponse downloadQRImageFile(ServiceReference1.downloadQRImageFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.facturatech.co/downloadQRImageFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.downloadQRImageFileResponse> downloadQRImageFileAsync(ServiceReference1.downloadQRImageFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.uploadInvoiceFileRequestBody Body;
        
        public uploadInvoiceFileRequest()
        {
        }
        
        public uploadInvoiceFileRequest(ServiceReference1.uploadInvoiceFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlBase64;
        
        public uploadInvoiceFileRequestBody()
        {
        }
        
        public uploadInvoiceFileRequestBody(string username, string password, string xmlBase64)
        {
            this.username = username;
            this.password = password;
            this.xmlBase64 = xmlBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.uploadInvoiceFileResponseBody Body;
        
        public uploadInvoiceFileResponse()
        {
        }
        
        public uploadInvoiceFileResponse(ServiceReference1.uploadInvoiceFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_ws uploadInvoiceFileResult;
        
        public uploadInvoiceFileResponseBody()
        {
        }
        
        public uploadInvoiceFileResponseBody(ServiceReference1.response_ws uploadInvoiceFileResult)
        {
            this.uploadInvoiceFileResult = uploadInvoiceFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileLayoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileLayout", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.uploadInvoiceFileLayoutRequestBody Body;
        
        public uploadInvoiceFileLayoutRequest()
        {
        }
        
        public uploadInvoiceFileLayoutRequest(ServiceReference1.uploadInvoiceFileLayoutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileLayoutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlBase64;
        
        public uploadInvoiceFileLayoutRequestBody()
        {
        }
        
        public uploadInvoiceFileLayoutRequestBody(string username, string password, string xmlBase64)
        {
            this.username = username;
            this.password = password;
            this.xmlBase64 = xmlBase64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadInvoiceFileLayoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uploadInvoiceFileLayoutResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.uploadInvoiceFileLayoutResponseBody Body;
        
        public uploadInvoiceFileLayoutResponse()
        {
        }
        
        public uploadInvoiceFileLayoutResponse(ServiceReference1.uploadInvoiceFileLayoutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class uploadInvoiceFileLayoutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_ws uploadInvoiceFileLayoutResult;
        
        public uploadInvoiceFileLayoutResponseBody()
        {
        }
        
        public uploadInvoiceFileLayoutResponseBody(ServiceReference1.response_ws uploadInvoiceFileLayoutResult)
        {
            this.uploadInvoiceFileLayoutResult = uploadInvoiceFileLayoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentStatusFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentStatusFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.documentStatusFileRequestBody Body;
        
        public documentStatusFileRequest()
        {
        }
        
        public documentStatusFileRequest(ServiceReference1.documentStatusFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class documentStatusFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string transaccionID;
        
        public documentStatusFileRequestBody()
        {
        }
        
        public documentStatusFileRequestBody(string username, string password, string transaccionID)
        {
            this.username = username;
            this.password = password;
            this.transaccionID = transaccionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class documentStatusFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="documentStatusFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.documentStatusFileResponseBody Body;
        
        public documentStatusFileResponse()
        {
        }
        
        public documentStatusFileResponse(ServiceReference1.documentStatusFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class documentStatusFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_docs documentStatusFileResult;
        
        public documentStatusFileResponseBody()
        {
        }
        
        public documentStatusFileResponseBody(ServiceReference1.response_docs documentStatusFileResult)
        {
            this.documentStatusFileResult = documentStatusFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadXMLFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadXMLFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadXMLFileRequestBody Body;
        
        public downloadXMLFileRequest()
        {
        }
        
        public downloadXMLFileRequest(ServiceReference1.downloadXMLFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadXMLFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadXMLFileRequestBody()
        {
        }
        
        public downloadXMLFileRequestBody(string username, string password, string prefijo, string folio)
        {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadXMLFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadXMLFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadXMLFileResponseBody Body;
        
        public downloadXMLFileResponse()
        {
        }
        
        public downloadXMLFileResponse(ServiceReference1.downloadXMLFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadXMLFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_xml downloadXMLFileResult;
        
        public downloadXMLFileResponseBody()
        {
        }
        
        public downloadXMLFileResponseBody(ServiceReference1.response_xml downloadXMLFileResult)
        {
            this.downloadXMLFileResult = downloadXMLFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadPDFFileRequestBody Body;
        
        public downloadPDFFileRequest()
        {
        }
        
        public downloadPDFFileRequest(ServiceReference1.downloadPDFFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadPDFFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadPDFFileRequestBody()
        {
        }
        
        public downloadPDFFileRequestBody(string username, string password, string prefijo, string folio)
        {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadPDFFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadPDFFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadPDFFileResponseBody Body;
        
        public downloadPDFFileResponse()
        {
        }
        
        public downloadPDFFileResponse(ServiceReference1.downloadPDFFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadPDFFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_pdf downloadPDFFileResult;
        
        public downloadPDFFileResponseBody()
        {
        }
        
        public downloadPDFFileResponseBody(ServiceReference1.response_pdf downloadPDFFileResult)
        {
            this.downloadPDFFileResult = downloadPDFFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadCUFEFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadCUFEFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadCUFEFileRequestBody Body;
        
        public downloadCUFEFileRequest()
        {
        }
        
        public downloadCUFEFileRequest(ServiceReference1.downloadCUFEFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadCUFEFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadCUFEFileRequestBody()
        {
        }
        
        public downloadCUFEFileRequestBody(string username, string password, string prefijo, string folio)
        {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadCUFEFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadCUFEFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadCUFEFileResponseBody Body;
        
        public downloadCUFEFileResponse()
        {
        }
        
        public downloadCUFEFileResponse(ServiceReference1.downloadCUFEFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadCUFEFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_cufe downloadCUFEFileResult;
        
        public downloadCUFEFileResponseBody()
        {
        }
        
        public downloadCUFEFileResponseBody(ServiceReference1.response_cufe downloadCUFEFileResult)
        {
            this.downloadCUFEFileResult = downloadCUFEFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadQRFileRequestBody Body;
        
        public downloadQRFileRequest()
        {
        }
        
        public downloadQRFileRequest(ServiceReference1.downloadQRFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadQRFileRequestBody()
        {
        }
        
        public downloadQRFileRequestBody(string username, string password, string prefijo, string folio)
        {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadQRFileResponseBody Body;
        
        public downloadQRFileResponse()
        {
        }
        
        public downloadQRFileResponse(ServiceReference1.downloadQRFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_qr downloadQRFileResult;
        
        public downloadQRFileResponseBody()
        {
        }
        
        public downloadQRFileResponseBody(ServiceReference1.response_qr downloadQRFileResult)
        {
            this.downloadQRFileResult = downloadQRFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRImageFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRImageFile", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadQRImageFileRequestBody Body;
        
        public downloadQRImageFileRequest()
        {
        }
        
        public downloadQRImageFileRequest(ServiceReference1.downloadQRImageFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRImageFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefijo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string folio;
        
        public downloadQRImageFileRequestBody()
        {
        }
        
        public downloadQRImageFileRequestBody(string username, string password, string prefijo, string folio)
        {
            this.username = username;
            this.password = password;
            this.prefijo = prefijo;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadQRImageFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="downloadQRImageFileResponse", Namespace="http://webservice.facturatech.co/", Order=0)]
        public ServiceReference1.downloadQRImageFileResponseBody Body;
        
        public downloadQRImageFileResponse()
        {
        }
        
        public downloadQRImageFileResponse(ServiceReference1.downloadQRImageFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.facturatech.co/")]
    public partial class downloadQRImageFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.response_qr_image_file downloadQRImageFileResult;
        
        public downloadQRImageFileResponseBody()
        {
        }
        
        public downloadQRImageFileResponseBody(ServiceReference1.response_qr_image_file downloadQRImageFileResult)
        {
            this.downloadQRImageFileResult = downloadQRImageFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WSV2PROSoapChannel : ServiceReference1.WSV2PROSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WSV2PROSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WSV2PROSoap>, ServiceReference1.WSV2PROSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSV2PROSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSV2PROSoapClient.GetBindingForEndpoint(endpointConfiguration), WSV2PROSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSV2PROSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSV2PROSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSV2PROSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSV2PROSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSV2PROSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.uploadInvoiceFileResponse ServiceReference1.WSV2PROSoap.uploadInvoiceFile(ServiceReference1.uploadInvoiceFileRequest request)
        {
            return base.Channel.uploadInvoiceFile(request);
        }
        
        public ServiceReference1.response_ws uploadInvoiceFile(string username, string password, string xmlBase64)
        {
            ServiceReference1.uploadInvoiceFileRequest inValue = new ServiceReference1.uploadInvoiceFileRequest();
            inValue.Body = new ServiceReference1.uploadInvoiceFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            ServiceReference1.uploadInvoiceFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).uploadInvoiceFile(inValue);
            return retVal.Body.uploadInvoiceFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.uploadInvoiceFileResponse> ServiceReference1.WSV2PROSoap.uploadInvoiceFileAsync(ServiceReference1.uploadInvoiceFileRequest request)
        {
            return base.Channel.uploadInvoiceFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.uploadInvoiceFileResponse> uploadInvoiceFileAsync(string username, string password, string xmlBase64)
        {
            ServiceReference1.uploadInvoiceFileRequest inValue = new ServiceReference1.uploadInvoiceFileRequest();
            inValue.Body = new ServiceReference1.uploadInvoiceFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            return ((ServiceReference1.WSV2PROSoap)(this)).uploadInvoiceFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.uploadInvoiceFileLayoutResponse ServiceReference1.WSV2PROSoap.uploadInvoiceFileLayout(ServiceReference1.uploadInvoiceFileLayoutRequest request)
        {
            return base.Channel.uploadInvoiceFileLayout(request);
        }
        
        public ServiceReference1.response_ws uploadInvoiceFileLayout(string username, string password, string xmlBase64)
        {
            ServiceReference1.uploadInvoiceFileLayoutRequest inValue = new ServiceReference1.uploadInvoiceFileLayoutRequest();
            inValue.Body = new ServiceReference1.uploadInvoiceFileLayoutRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            ServiceReference1.uploadInvoiceFileLayoutResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).uploadInvoiceFileLayout(inValue);
            return retVal.Body.uploadInvoiceFileLayoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.uploadInvoiceFileLayoutResponse> ServiceReference1.WSV2PROSoap.uploadInvoiceFileLayoutAsync(ServiceReference1.uploadInvoiceFileLayoutRequest request)
        {
            return base.Channel.uploadInvoiceFileLayoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.uploadInvoiceFileLayoutResponse> uploadInvoiceFileLayoutAsync(string username, string password, string xmlBase64)
        {
            ServiceReference1.uploadInvoiceFileLayoutRequest inValue = new ServiceReference1.uploadInvoiceFileLayoutRequest();
            inValue.Body = new ServiceReference1.uploadInvoiceFileLayoutRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.xmlBase64 = xmlBase64;
            return ((ServiceReference1.WSV2PROSoap)(this)).uploadInvoiceFileLayoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.documentStatusFileResponse ServiceReference1.WSV2PROSoap.documentStatusFile(ServiceReference1.documentStatusFileRequest request)
        {
            return base.Channel.documentStatusFile(request);
        }
        
        public ServiceReference1.response_docs documentStatusFile(string username, string password, string transaccionID)
        {
            ServiceReference1.documentStatusFileRequest inValue = new ServiceReference1.documentStatusFileRequest();
            inValue.Body = new ServiceReference1.documentStatusFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.transaccionID = transaccionID;
            ServiceReference1.documentStatusFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).documentStatusFile(inValue);
            return retVal.Body.documentStatusFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.documentStatusFileResponse> ServiceReference1.WSV2PROSoap.documentStatusFileAsync(ServiceReference1.documentStatusFileRequest request)
        {
            return base.Channel.documentStatusFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.documentStatusFileResponse> documentStatusFileAsync(string username, string password, string transaccionID)
        {
            ServiceReference1.documentStatusFileRequest inValue = new ServiceReference1.documentStatusFileRequest();
            inValue.Body = new ServiceReference1.documentStatusFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.transaccionID = transaccionID;
            return ((ServiceReference1.WSV2PROSoap)(this)).documentStatusFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.downloadXMLFileResponse ServiceReference1.WSV2PROSoap.downloadXMLFile(ServiceReference1.downloadXMLFileRequest request)
        {
            return base.Channel.downloadXMLFile(request);
        }

        /* public ServiceReference1.response_xml downloadXMLFile(string username, string password, string prefijo, string folio)
         {
             ServiceReference1.downloadXMLFileRequest inValue = new ServiceReference1.downloadXMLFileRequest();
             inValue.Body = new ServiceReference1.downloadXMLFileRequestBody();
             inValue.Body.username = username;
             inValue.Body.password = password;
             inValue.Body.prefijo = prefijo;
             inValue.Body.folio = folio;
             ServiceReference1.downloadXMLFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).downloadXMLFile(inValue);
             return retVal.Body.downloadXMLFileResult;
         }*/

        public ServiceReference1.response_xml downloadXMLFile(string username, string password, string prefijo, string folio)
        {
            var inValue = new ServiceReference1.downloadXMLFileRequest
            {
                Body = new ServiceReference1.downloadXMLFileRequestBody
                {
                    username = username,
                    password = password,
                    prefijo = prefijo,
                    folio = folio
                }
            };

            var retVal = ((ServiceReference1.WSV2PROSoap)this).downloadXMLFile(inValue);
            return retVal.Body.downloadXMLFileResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.downloadXMLFileResponse> ServiceReference1.WSV2PROSoap.downloadXMLFileAsync(ServiceReference1.downloadXMLFileRequest request)
        {
            return base.Channel.downloadXMLFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.downloadXMLFileResponse> downloadXMLFileAsync(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadXMLFileRequest inValue = new ServiceReference1.downloadXMLFileRequest();
            inValue.Body = new ServiceReference1.downloadXMLFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            return ((ServiceReference1.WSV2PROSoap)(this)).downloadXMLFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.downloadPDFFileResponse ServiceReference1.WSV2PROSoap.downloadPDFFile(ServiceReference1.downloadPDFFileRequest request)
        {
            return base.Channel.downloadPDFFile(request);
        }
        
        public ServiceReference1.response_pdf downloadPDFFile(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadPDFFileRequest inValue = new ServiceReference1.downloadPDFFileRequest();
            inValue.Body = new ServiceReference1.downloadPDFFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            ServiceReference1.downloadPDFFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).downloadPDFFile(inValue);
            return retVal.Body.downloadPDFFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.downloadPDFFileResponse> ServiceReference1.WSV2PROSoap.downloadPDFFileAsync(ServiceReference1.downloadPDFFileRequest request)
        {
            return base.Channel.downloadPDFFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.downloadPDFFileResponse> downloadPDFFileAsync(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadPDFFileRequest inValue = new ServiceReference1.downloadPDFFileRequest();
            inValue.Body = new ServiceReference1.downloadPDFFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            return ((ServiceReference1.WSV2PROSoap)(this)).downloadPDFFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.downloadCUFEFileResponse ServiceReference1.WSV2PROSoap.downloadCUFEFile(ServiceReference1.downloadCUFEFileRequest request)
        {
            return base.Channel.downloadCUFEFile(request);
        }
        
        public ServiceReference1.response_cufe downloadCUFEFile(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadCUFEFileRequest inValue = new ServiceReference1.downloadCUFEFileRequest();
            inValue.Body = new ServiceReference1.downloadCUFEFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            ServiceReference1.downloadCUFEFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).downloadCUFEFile(inValue);
            return retVal.Body.downloadCUFEFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.downloadCUFEFileResponse> ServiceReference1.WSV2PROSoap.downloadCUFEFileAsync(ServiceReference1.downloadCUFEFileRequest request)
        {
            return base.Channel.downloadCUFEFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.downloadCUFEFileResponse> downloadCUFEFileAsync(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadCUFEFileRequest inValue = new ServiceReference1.downloadCUFEFileRequest();
            inValue.Body = new ServiceReference1.downloadCUFEFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            return ((ServiceReference1.WSV2PROSoap)(this)).downloadCUFEFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.downloadQRFileResponse ServiceReference1.WSV2PROSoap.downloadQRFile(ServiceReference1.downloadQRFileRequest request)
        {
            return base.Channel.downloadQRFile(request);
        }
        
        public ServiceReference1.response_qr downloadQRFile(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadQRFileRequest inValue = new ServiceReference1.downloadQRFileRequest();
            inValue.Body = new ServiceReference1.downloadQRFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            ServiceReference1.downloadQRFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).downloadQRFile(inValue);
            return retVal.Body.downloadQRFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.downloadQRFileResponse> ServiceReference1.WSV2PROSoap.downloadQRFileAsync(ServiceReference1.downloadQRFileRequest request)
        {
            return base.Channel.downloadQRFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.downloadQRFileResponse> downloadQRFileAsync(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadQRFileRequest inValue = new ServiceReference1.downloadQRFileRequest();
            inValue.Body = new ServiceReference1.downloadQRFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            return ((ServiceReference1.WSV2PROSoap)(this)).downloadQRFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.downloadQRImageFileResponse ServiceReference1.WSV2PROSoap.downloadQRImageFile(ServiceReference1.downloadQRImageFileRequest request)
        {
            return base.Channel.downloadQRImageFile(request);
        }
        
        public ServiceReference1.response_qr_image_file downloadQRImageFile(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadQRImageFileRequest inValue = new ServiceReference1.downloadQRImageFileRequest();
            inValue.Body = new ServiceReference1.downloadQRImageFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            ServiceReference1.downloadQRImageFileResponse retVal = ((ServiceReference1.WSV2PROSoap)(this)).downloadQRImageFile(inValue);
            return retVal.Body.downloadQRImageFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.downloadQRImageFileResponse> ServiceReference1.WSV2PROSoap.downloadQRImageFileAsync(ServiceReference1.downloadQRImageFileRequest request)
        {
            return base.Channel.downloadQRImageFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.downloadQRImageFileResponse> downloadQRImageFileAsync(string username, string password, string prefijo, string folio)
        {
            ServiceReference1.downloadQRImageFileRequest inValue = new ServiceReference1.downloadQRImageFileRequest();
            inValue.Body = new ServiceReference1.downloadQRImageFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.prefijo = prefijo;
            inValue.Body.folio = folio;
            return ((ServiceReference1.WSV2PROSoap)(this)).downloadQRImageFileAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSV2PROSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSV2PROSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSV2PROSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.facturatech.co/v2/BETA/WSV2PRO.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSV2PROSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.facturatech.co/v2/BETA/WSV2PRO.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSV2PROSoap,
            
            WSV2PROSoap12,
        }
    }
}
